# Generated by Django 5.1.6 on 2025-02-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("app", "App"),
                            ("product", "Product"),
                            ("branding", "Branding"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image", models.ImageField(upload_to="portfolio/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
